### ISSUE TITLE
Write some documentation for debugger support

### ISSUE THREAD

**Issue by PeterWone** [sebastienros/jint#1016]
@Jither You've done so much work on this, it would be a tragedy for it to go unused because there's no documentation whatsoever. Or if there is, it's not turning up in searches.

Is the debugger interface based on some standard for which docs are available?

Perhaps a worked comprehensive demonstration by using it from a well known debug client implementation like Visual Studio Code. This would not only show people how to use it, it would be a worthwhile piece of software in its own right.

**Comment by Jither** [comment]
There's a bit of indirect documentation in this semi-duplicate: https://github.com/sebastienros/jint/issues/674 - and the source documentation very much follows Chromium concepts and terminology.

Unfortunately, I have way too many projects going on at the moment. Started some work on implementing the DevTools protocol around the debugger (and adding support to Jint itself - mostly rewriting the Breakpoint implementation to be more intuitive and less error prone). But that's on hold too - and quite a bit has happened to Jint since I last looked at it: https://github.com/Jither/Jint.DevToolsProtocol

I do intend to look at it again at some point, but can't really say when that point will be. 😐 But until then (or until someone else jumps at it):

This pretty much demonstrates use of the main (breakpoint/stepping) API: https://github.com/Jither/Jint.DevToolsProtocol/blob/main/Jint.DevToolsProtocol/Protocol/Debugger.cs

The rest of the API really consists of the properties in https://github.com/sebastienros/jint/blob/main/Jint/Runtime/Debugger/DebugInformation.cs - which are all documented in the source.

**Comment by PeterWone** [comment]
I can see that it shouldn't be all on you. I'll look at this myself though I doubt work and my other project will allow a something this big.

Is the design of what you're building wholly original or based on some convention or another work?

**Comment by Jither** [comment]
It's really based on the API that was already in Jint before I started - just elaborated on it. The only change I've made to the public API itself is moving breakpoints into a separate class and adding more information to DebugInformation. All of that information is based on the DevTools protocol (i.e. https://chromedevtools.github.io/devtools-protocol/)

**Comment by Jither** [comment]
I've (manually) rebased the changes in the `devtools-protocol` branch in my fork onto the latest Jint changes and placed it in a new `debugger-improvements-4`, which I may make a pull request for soon. The `devtools-protocol` branch is now abandoned, and it's likely that I'll focus on implementing a DebugAdapter for VS Code as an example, rather than continue on the devtools protocol server.

The DebugAdapter approach has several advantages:

- Better documentation and stability
- Likely to get more attention by its developers, since DebugAdapter is more of a first class citizen in VS Code than devtools protocol is in Chromium.
- It doesn't have all the complications that come with browser debugging (which Jint obviously doesn't need anyway). Which also means it should have greater third party support (it already does - e.g. Visual Studio Debug Adapter Host in the Visual Studio IDE).

The terminology and concepts from DTP still apply, since most of them are derived from the ECMAscript specs anyway. I.e., there'll be no changes to scopes etc. (the DebugAdapter protocol includes the adapter specifying scope names etc., since they'll be different for different languages).

**Comment by PeterWone** [comment]
I'm very interested in this. At the moment I've faked it using VS Code's ability to debug JS. I use a loader module that injects mocks and imports the script I'm debugging. This hinges on all such scripts having a single consistent entry point, a `main` method.

The biggest problem is making sure that whatever C# objects I inject have semantics I can exactly match in JS.

Fortunately I control both sides of this equation, but a true Jint debugger injecting dotnet objects would be much better.

I have a successful VS Code extension so I'm no stranger to writing extensions, but working with `DebugAdapter` is new ground for me so I really don't know whether I can be much help. You tell me.

**Comment by Jither** [comment]
I'm working on something, but can't say when other projects take priority again. Have a minimal debugger extension set up (with hardcoded DebugAdapter executable paths etc.).

Started to implement the early communication (initialization, launch, set breakpoints), currently using Microsoft's unfortunately closed source C# library for managing the protocol itself. Just to try and get something up and running. But there's no integration with actual Jint yet - just mock responses to see if everything is working together. Since it took hours just to get VSCode and the DebugAdapter talking, because it's somewhat cumbersome to debug a VS extension that's running in the Extension Development Host, and which is calling an external executable directly, suppressing the terminal window.

Should help on things when I get one of the server interfaces set up (TCP or - probably simpler, and more secure in the long run - named pipe), so that the DebugAdapter can run in the Visual Studio debugger while VSCode is connecting to it.

Still having a hard time wrapping my head around the differences between devtools protocol and DebugAdapter. For example, devtools has methods for letting the debugging host supply script source through the protocol, while at a glance it appears that VSCode requires direct access to the files via path or URL to display and debug them - which limits its use to scripts that are actually hosted on a filesystem or web server. But I'm not all the way through the specs, so don't know if something shows up. In any event, most use cases should still be covered.

Will see if I can get a public repository of the experimental stuff up during the next week, so we can discuss things based on that.

**Comment by Jither** [comment]
Getting back to this one for at least a bit... Implementing my own DebugAdapter implementation rather than using the closed source library from Visual Studio (should be general purpose - i.e. could be used by other C# implemented interpreters/languages). Have around 50% of the communication (the essentials) implemented with the same mock responses, with (quickly implemented) support for connection through stdin/out, TCP and named pipes. Now looking into refactoring and combining it with the Jint DebugHandler - probably adding some additional API to the DebugHandler to support everything needed for the DebugAdapter protocol. That should also make it sufficient for just about any other debugger implementation.

But - just as last time - no promises that I won't be dragged away from it again.

**Comment by Jither** [comment]
Just an update: The DebugAdapter implementation is "done" (i.e., mostly has the API I want). Now started work on the Jint part of the equation. I'm trying to keep the core debug handling separate (i.e. handling of execution, step/break, exception handling), which should make it pretty much usable whether you're dealing with your own UI or a protocol like the DebugAdapter protocol or devtools. In other words, it should handle the part where Jint is running on one thread (which is blocked with a ManualResetEvent), while the UI/protocol server is running on another.

_Hope_ to finally make the work-in-progress repository public over the weekend or next week.

**Comment by PeterWone** [comment]
I'm crazy busy at work, I wish I had time to be involved.

**Comment by Jither** [comment]
> I'm crazy busy at work, I wish I had time to be involved.

No worries - hoping I'll get done this time (as opposed to the previous false starts). 🙂

The very-much-work-in-progress repo is public here: https://github.com/Jither/Jint.DebugAdapter

It's up and running, but still lots of bugs and missing functionality (and it requires changes in a pull request that hasn't been merged yet - since there's likely to be more changed needed to the main engine.

**Comment by Jither** [comment]
Example linked below of an interactive console debugger, which builds against the latest `main` branch, and shows many of the concepts. A tutorial/actual documentation might follow soonish. The example _tries_ to avoid having too much "nice to have" code, although I couldn't resist making it slightly prettier and somewhat more user friendly than an example needs to (or even should) be. 😋

The example is purely single threaded, so there's no real coverage of developing a debugger in e.g. WPF or a DebugServer, although the basic idea is described in comments - Jint.DebugAdapter shows more of that approach, although it's still unfinished and its threading is very flawed.

https://github.com/Jither/Jint.DebuggerExample

**Comment by lahma** [comment]
Closing this as we probably need volunteers to write the documentation. We can reopen / accept PRs on the subject.
