### ISSUE TITLE
dotnet-js array compatibility

### ISSUE THREAD

**Issue by PeterWone** [sebastienros/jint#1030]
If you inject a dotnet helper object with a method that returns an array, the array is a dotnet array object, not a JS array. This presents a raft of compatibility issues.

The case that prompted this observation returns an array of strings. This could be converted to a JS array of strings. It's probably not reasonable to expect this to happen automagically but the author of the helper could certainly do it in the helper method and return something more suitable. 

Could you provide some guidance on how to go about preparing a compatible object for the helper method to return?

* How to convert a primitive (int, float, string) to a `JsValue`
* How to construct a `JsValue` array and populate it with the `JsValue`s constructed from the values of the dotnet array

## Update
It appears there is already some automagical compatibility going on, but the `.forEach` method is not available. Possibly this is not yet implemented.

**Comment by lahma** [comment]
Could you please provide some example test cases to cover your use cases? 

Like whether it needs to be during injecting to engine (array from CLR code to engine as JS Array) or during interpretation (`obj.property.list.foreach` where `list` is a sub-property of object that would need to transform into JS array. The problem generally is that if Jint wraps an array/list instance it will become bound to JS rules instead of CLR rules which are more stricted and perform better.

**Comment by PeterWone** [comment]
> if Jint wraps an array/list instance it will become bound to JS rules instead of CLR rules which are more stricted and perform better

A helper is returning a C# `string[]` coming from `Directory.EnumerateFiles`. 

This code

```
filelist.foreach(filename => { ... });)
```
was throwing a null reference error because it couldn't find forEach on the dotnet array object.

I rewrote it as a for loop and that works fine, which is when I made the update.

There's a whole discussion to be had about this sort of compatibility issue. You could do special case handling and implement things like forEach, or just have a way to wrap injected objects when there are issues.
Since opening the issue I have

**Comment by lahma** [comment]
I think you can already achieve the thing you want with customizing object wrapping to set array prototype to objects:

https://github.com/sebastienros/jint/blob/9d8432606d20c884def5d62f06ff870c97302b69/Jint.Tests/Runtime/InteropTests.cs#L873-L905

**Comment by PeterWone** [comment]
That looks like just the ticket. I shall give it a try after I figure out the bug that's currently giving me trouble (Jint related but it works fine in my proof of concept so I'm quite sure it's not Jint).

**Comment by lahma** [comment]
> What are the penalties from doing that? Presumably there are some or that would be the default behaviour.

Sorry missed the question. I think it's not the default because I'm unsure if there's consensus which types should be "re-prototyped". Just plain array? maybe IList? HashSet? when should it be TypedArray prototype? so it could get confusing

Jint currently doesn't automatically change the prototype, might change at some point or might be left for end users to figure out indefinitely 🙂 

Anything else here or can we close the issue?

**Comment by KurtGokhan** [comment]
Maybe it could be possible that `Symbol.iterator` property returns an iterator for C# IEnumerators, so that they can be passed to `Array.from`, `for..of` and other stuff that expects iterators. I think it is worth checking.

**Comment by lahma** [comment]
That scenario should already work, but these enumerables won't get `filter`, `map` etc functions automatically without manual prototype assignment.

**Comment by lahma** [comment]
Closing, we can reopen if more is to be done.

**Comment by sfmskywalker** [comment]
I stumbled upon this amazing thread today while looking for a way to have .NET Lists be treated as JS Arrays in order to allow JS expression authors to leverage typical Array functions like `filter` and that unit test works perfectly for our use case 🎉 

@lahma If you agree that it is useful enough, I will propose a small PR that adds this to the README.

**Comment by sfmskywalker** [comment]
I noticed that somewhere between version `3.0.0-beta-2057` and `3.0.0`, the `ObjectWrapper.IsArrayLike` property changed from `public` to `internal`. Looking at the `ObjectWrapper` class (3.0.0), it isn't immediately obvious to me how this should be adapted. It works in the unit tests because Jint exposes its internals to the test projects, but it will break our use cases when updating to 3.0.0.

If this was an undesired effect, Id be happy to submit a PR changing it back to public.

**Comment by lahma** [comment]
There's a reason for `IsArrayLike` not being public, it's not always easy to interpret. The Jint debugger example adopted to read the `Length`, which does not fully mean something being array-like. You can also cast to some known types (JsArray, JsTypedArray...). Basically `{ name: 'John', length: 42 }` would be array-like 🤷🏻‍♂️ 

For interop you can always attach the array prototype if it seems like suitable (Jint doesn't do this because it doesn't know if it's right). A failing test case presenting the need is always welcome. I did hide a lot of things just to be sure not to regret exposing them later on 😉

**Comment by sfmskywalker** [comment]
I see, makes sense actually! I should be responsible for determining if a target value is deemed to be treated as an array, since I have more context about a given use case 👍🏻

**Comment by sfmskywalker** [comment]
It would seem that the `SetPrototypeOf` and `engine.Realm` members are also made internal.
Would you happen to know offhand if there's supposed to be a different API to attach the array prototype?

```csharp
 var instance = new ObjectWrapper(engine, target);

// The following no longer compiles when referencing 3.0.0:                
instance.SetPrototypeOf(engine.Realm.Intrinsics.Array.PrototypeObject);
```

**Comment by lahma** [comment]
There was a recent PR to improve the test case: https://github.com/sebastienros/jint/pull/1767

Basically it's now `Prototype` set property. Trying to make the API more .NET-like.

**Comment by sfmskywalker** [comment]
Actually, I think I found it: there is a public `ProtoType` property I can set. Thanks for rubber ducking 😄

**Comment by sfmskywalker** [comment]
> There was a recent PR to improve the test case: #1767
> 
> Basically it's now `Prototype` set property. Trying to make the API more .NET-like.

Got it - then it is confirmed 👍🏻

**Comment by sfmskywalker** [comment]
I guess the final piece of the puzzle is how to get a reference to an actual `ArrayPrototype` instance, given that `Realms` of the `Engine` is now also internal 🤔

**Comment by sfmskywalker** [comment]
Aha - found it too:

```csharp
instance.Prototype = engine.Intrinsics.Array.PrototypeObject;
```

**Comment by sfmskywalker** [comment]
This worked out flawlessly - thanks @lahma for the super awesome support, I really appreciate it 🙏🏻

**Comment by lahma** [comment]
The final tweaks for 3.0 were quite aggressive, please ping for possible further obstacles.

**Comment by sebastienros** [comment]
> The final tweaks for 3.0.0 were quite aggressive

I love that `GetCompletionValue()` is now hidden behind `engine.Evaluate()`. Way easier to use.

**Comment by sfmskywalker** [comment]
It certainly does feel quite polished - really outstanding work.

**Comment by JBBianchi** [comment]
> I see, makes sense actually! I should be responsible for determining if a target value is deemed to be treated as an array, since I have more context about a given use case 👍🏻

Would you mind sharing your workaround the restriction of `IsArrayLike` ?

**Comment by sfmskywalker** [comment]
Not at all, here you go:

https://github.com/elsa-workflows/elsa-core/commit/a1c30facbae44590ebd8d5662e052109950d535c

**Comment by lahma** [comment]
And here's some logic Jint uses at the moment https://github.com/sebastienros/jint/blob/main/Jint/Runtime/Interop/TypeDescriptor.cs
