### ISSUE TITLE
internal interface `IConstructor`

### ISSUE THREAD

**Issue by lahma** [sebastienros/jint#1144]
### Discussed in https://github.com/sebastienros/jint/discussions/1141

<div type='discussions-op-text'>

<sup>Originally posted by **viceice** April 22, 2022</sup>
Was this intentional to no longer make that interface public? I use that for a custom type, which implements this interface.

https://github.com/sebastienros/jint/blob/fe4ee89b85a8ea2bd7d3406b55e6597df368b58d/Jint/Native/IConstructor.cs#L5

I'm basicall doing something like this:
https://github.com/sebastienros/jint/blob/fe4ee89b85a8ea2bd7d3406b55e6597df368b58d/Jint.Tests/Runtime/Domain/UuidConstructor.cs#L11

changed in [`v3.0.0-beta-2038`](https://github.com/sebastienros/jint/releases/tag/v3.0.0-beta-2038) via
- #1047</div>

**Comment by viceice** [comment]
Can we make those interfaces public again until a better solution is found?

**Comment by dan3988** [comment]
Could `FunctionInstance` not implement `IConstructor`, with a virtual implementation that throws a type error by default? That way `IConstructor` can be made internal and we can still create custom constructors by overriding that method.

**Comment by lahma** [comment]
@dan3988 what's your use case, I'd favor something simpler like [the model I'm proposing in this PR](https://github.com/sebastienros/jint/pull/1183). Building against `IConstructor` usually means that you are implementing the ECMA spec.

**Comment by dan3988** [comment]
@lahma I have some custom classes I've implemented similarly to the ECMA classes inside Jint/Native, where I have a separate C# class for the constructor, prototype and instance.

**Comment by lahma** [comment]
Sorry to sound like a broken record,  but can you give a more specific example. Doing the constructor-prototype-instance route seems quite involved compared to what it would be if we could make the interop do the leg work.

**Comment by dan3988** [comment]
I've extracted some of the code from the project into a [repo](https://github.com/dan3988/JintExample) with some examples of javascript classes:
-  [WmDate](https://github.com/dan3988/JintExample/blob/master/WmDate.cs)
-  [WmTime](https://github.com/dan3988/JintExample/blob/master/WmTime.cs)
-  [Uuid](https://github.com/dan3988/JintExample/blob/master/Uuid.cs)

There are 30-40 classes implemented this way in our project. It was written this way as we wanted the following
- Classes in the script that inherit other custom classes, so that `instanceof` would work in our scripts
- Classes that have a constructor object, but are not instantiatable inside the script (like the `Window` constructor in a browser)
- A way of adding properties with a different name to the C# method / property
- A way of adding properties with symbol keys, such as `Symbol.toPrimitive`

**Comment by viceice** [comment]
maybe a constructor base class is enough

**Comment by EnCey** [comment]
*bump*, I'm facing the same problem now 😅 
my use case is to call async .NET methods, which I've gotten to work, but it blocks me from going the `TypeReference` route, at least I don't see how that would work.

A constructor base class could also set the `Function.PrototypeObject`, which is something the `UuidConstructor` example does and feels like a good default.
