### ISSUE TITLE
Import module from evaluated script, ambiguous import and return value

### ISSUE THREAD

**Issue by kpko** [sebastienros/jint#1219]
Hi,

I'm trying to use the new module feature in Jint but I can't get it to work as in other JavaScript engines (i.e. ClearScript). I want to evaluate a script thats returning a result and import methods from a c# based module.

```csharp
using System.Reflection;
using Jint;

var engine = new Engine();

var module = new TestModule();
engine.AddModule("test", b =>
{
    b.ExportObject("module", module);
    foreach (var method in module.GetType().GetMethods(BindingFlags.Public | BindingFlags.Instance))
    {
        b.AddSource($"export function {method.Name}() {{ module.{method.Name}.apply(module, arguments) }}");
    }
});

var result = engine.Evaluate("import {TestMethod} from 'test'; return TestMethod()");
Console.WriteLine(result);

public class TestModule
{
    public void TestMethod()
    {
        Console.WriteLine("Hello, World!");
    }
}
```

When I try to evaluate the code snippet, I get an exception that modules can't be imported outside of a module. Can I somehow indicate, that the script that I want to evaluate should be evaluated in a "module context"? Also, is there a better way to expose every method/member of an object except for the workaround I implemented with AddSource? 

I tried creating the snippet as a module itself and evaluate it. 

```csharp
engine.AddModule("main", b => b.AddSource("import {TestMethod} from 'test'; TestMethod()"));
var i = engine.ImportModule("main");
```

Do I have access to the completion value of the script, i.e. the result of testMethod in my case? Can I return from a module or do I have to use export default?

Thanks in advance. I'm excited to see if my use case works in Jint as it does in ClearScript :)

**Comment by lahma** [comment]
Pinging @christianrondeau for possible insights.

**Comment by christianrondeau** [comment]
Returning a value in a module isn't supported in node.js. For example, when you execute a script `return 0;` with `node script.mjs` it will throw `SyntaxError: Illegal return statement`.

I would recommend using `export default TestMethod();` or `export const result = TestMethod();` instead of relying on the completion value.

This being said, it wouldn't be (probably) very difficult to give access to the return value, but it would be tricky to provide a clean way to access it. Right now you can see in `CyclicModuleRecord.Evaluate`, the result of `InnerModuleEvaluation` is the completion you're looking for, but unless there's an error it's dropped in favor of the module loading promise. It'd be possible to make a method like "EvaluateModule" that would return the completion and drop the promise (weird) or "EvaluateAndImportModule" which would return both, if the maintainers agree; but it would not be standard.

Or, implement the ability to import a module in a script, which is also unsupported in the ecmascript specifications but would probably be desirable (but not necessarily obvious in the code, especially for async modules). That's probably what ClearScript does. I think @lahma and @sebastienros wanted that too (being able to import a module from a script), so I'm sure a PR would be welcome :) If you (or someone) wants to try, ping me I can share what my problems were in doing this (though it's been a while).

**Comment by lahma** [comment]
Had a faint memory recently, was this one of the cases that one should use the dynamic import (`const m = import('./my-module.js')`) ? 🤔

**Comment by christianrondeau** [comment]
You're right, I forgot we did support dynamic import: https://github.com/sebastienros/jint/blob/main/Jint.Tests/Runtime/ModuleTests.cs#L94

**Comment by lahma** [comment]
@kpko have you had the chance to try out the `import()` call?

**Comment by kpko** [comment]
Yes, I'm using import() in my scripts now and it seems to work great. I lose some interoperability because the syntax is different from V8 and we can't use the same import {} from.. statements. It would be great if we would have some support for that in the future :)

Thank you.

**Comment by lahma** [comment]
The import syntax should be standard, so sounds bad if it doesn't work the same way between the runtime.

**Comment by lahma** [comment]
Closing this as now import syntax is available and some import fixes have been done. Please open more specific issues if needed.
