### ISSUE TITLE
Jint 3.x can not work in unity

### ISSUE THREAD

**Issue by GDdark** [sebastienros/jint#1234]
there is an error when import the jint@latest in nuget.

Assets/NewBehaviourScript.cs(23,9): error CS0012: The type 'Script' is defined in an assembly that is not referenced. You must add a reference to assembly 'Esprima, Version=2.1.2.0, Culture=neutral, PublicKeyToken=2e92ba9c8d81157f'.

Jint Version: jint.3.0.0-beta-2038
Unity Version: 2021.3.2f1

**Comment by lahma** [comment]
Have you tried to add the reference?

**Comment by lahma** [comment]
We can reopen if adding reference didn't help and there's a good repro for the issue.

**Comment by arsi0001** [comment]
Hello,
I'm also using Jint in a Unity project and updated Jint today to the newest version. Now I get a similiar message:

1. I'm adding [Jint 3.0.0-beta-2043](https://www.nuget.org/packages/Jint/3.0.0-beta-2043) to my projekt. After importing the new DLL I get for every jint-line in my project this message
`error CS0012: The type 'Script' is defined in an assembly that is not referenced. You must add a reference to assembly 'Esprima, Version=3.0.0.0, Culture=neutral, PublicKeyToken=2e92ba9c8d81157f'.`

2. I 'm adding [Esprima 3.0.0-beta-9](https://www.nuget.org/packages/Esprima/3.0.0-beta-9#versions-body-tab). After importing that I get the next message
`Error: Could not load signature of HexConverter:get_CharToHexLookup due to: Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:<unknown type> member:(null) signature:<none>`

@GDdark How did you fix your problem? Did it run after importing Esprima?
@lahma Have you already faced this problem?

**Comment by lahma** [comment]
Have you tried adding a reference to [System.Memory](https://www.nuget.org/packages/System.Memory/) (>= 4.5.4)

**Comment by arsi0001** [comment]
I updated my first post with more reference errors and how to fix it
