### ISSUE TITLE
Can't compile UWP project with .NET Native compiler

### ISSUE THREAD

**Issue by LilyStilson** [sebastienros/jint#1378]
Currently, Microsoft requires all UWP apps to be compiled with .NET Native compiler toolchain to be released in Microsoft Store.
But when I'm trying to compile a `x64` `Release` configuration with Jint added to a project - compilation just fails.

It it only possible to build `x86` `Release` configuration. Every other (`ARM`, `ARM64` and `x64`) configuration is failing to build with `nutc_driver.exe` always exiting with some error code. `Debug` configurations don't have the same problem, since the .NET Native toolchain is not required with them.

I have attached a recording of this happening with `x64` `Release` configuration. See how the project builds just fine when Jint is not installed, and how it fails to be built after I installed latest version of Jint.

https://www.youtube.com/watch?v=HOy67bU3fVc

Jint versions tried:
- `3.0.0-beta-2044`
- `3.0.0-preview-386`

**Comment by lahma** [comment]
I don't have any experience in this area, but following the advice here: https://github.com/dotnet/corert/issues/7408#issuecomment-490601593 and commenting out the `<Assembly Name="*Application*" Dynamic="Required All" />` made the solution compile. 

Can you try that out?

**Comment by lahma** [comment]
We can reopen if more specific to do on Jint's side.

**Comment by cumbala** [comment]
@lahma Before submitting this issue report, OF COURSE I have tried alost all the possible suggestions out there in the web. Including yours, removing pieces of code one-by-one, moving everything to a different project, using x64 compiler, increasing compiler memory usage. Only disabling .NET Native compiler entirely solved the issue, but not the global problem - can't submit app to the MS Store.

The only things I haven't tried yet are migrating my app to WinUI, reinstalling VS/Rider and migrating to a different JS library.

**Comment by sebastienros** [comment]
@cumbala If you could find a specific version after which it doesn't work anymore that might be helpful since we could then understand what were the changes that broke it. Assuming it used to work with 3.0-*.

If you could also find what are the requirements for an app to be able to compile with the native compiler it could also help us understand where the problem is.

One outcome may be to have a custom compilation flag to remove the features that prevent Jint from compiling natively.

**Comment by lahma** [comment]
Hmm.. @cumbala I'm not sure how you relate to he original poster @LilyStilson , but let's follow along that you have a double identity.

Anyway, I think it would great if you find some time to investigate possible causes for this as I think the main contributors are neither running Jint in such restricted environment nor UWP experts. I'd suspect when it comes to UWP development it should be easier for you to investigate and diagnose the root cause, knowing the platform.
