### ISSUE TITLE
CLR Primitive types always converted to double

### ISSUE THREAD

**Issue by fanoI** [sebastienros/jint#329]
The issue could be divided in two parts:

1. It is not actually possible to define them in easy way (var aFloat = 42.0f does not work)
2. The value is converted always to double nevertheless

These are two examples in which I show the issue.

First case with System.Decimal:

```           
engine.Execute(@"
                              //var f = 42.0f;
                              var d1 = System.Decimal.Parse('0,2');
                              var d2 = System.Decimal.Parse('3');
                              var result = d1 * d2;
                              System.Console.WriteLine('result is ' + result); // 0.600000000000001 (instead of 0.6!)
                           ");
```

This case is with long:
```
            engine.Execute(@"
                                var longMax = System.Int64.Parse('9223372036854775807');
                                System.Console.WriteLine('longMax is ' + longMax); // 9223372036854776000
                            ");
```
In all the two case var should be of the proper type (System.Decimal and System.Int64) and no conversion should occur.

To overcome the first point maybe a CLR Primitive type could declared in this way in javascript:

```
var aDecimal = new System.Decimal(42.0);
```
Obviously the "42.0" should not be implicitly converted to double or again we will lose precision!

**Comment by sebastienros** [comment]
By design all numbers in JavaScript are double, and converted this way by Jint, c.f. http://www.ecma-international.org/ecma-262/6.0/#sec-terms-and-definitions-number-value

> Number value
primitive value corresponding to a double-precision 64-bit binary format IEEE 754-2008 value

**Comment by fanoI** [comment]
Well Jint extends Javascript to interoperate with the CLR right?

So what is the difference with this:

```
        var file = new System.IO.StreamWriter('log.txt');
        file.WriteLine('Hello World !');
        file.Dispose();
```
and this?

```
      var longMax = System.Int64.Parse('9223372036854775807');
```

I see this to be equivalent to the following C# code:
```
    Object longMax = System.Int64.Parse('9223372036854775807');
```

It is not important in this case if the Value Type is boxed if this will permit to retain its precision / range.
What do you think?

**Comment by sebastienros** [comment]
Jint interoperates with the CLR, right, and all numbers in Jint are converted to `double` to match what JavaScript expects to handle. Precision is one factor of variation, but ranges are too. For instance because JS expects double values, it has a specific behavior with regards to what's the min/max value of a number, and it's specified in the specification. There are many tests in ECMA 251 to ensure these ranges are handled correctly.

In your example with strings there are no issues because JavaScript also support unicode, so strings are compatible. Booleans are converted too, and no issues, DateTime are also converted to numbers automatically though. And we can't change the behavior of an expression based on the statement - in your example we can't "not convert" the Int64 just because it's assigned to an Object, what would be the `class` of this object?

So no, I don't think we should retain the precision/range. I understand that round-trips from one language to the other might lead to type mismatches.
