### ISSUE TITLE
workaround for Cyclic references?

### ISSUE THREAD

**Issue by 0xFireball** [sebastienros/jint#351]
I'm getting a `Cyclic reference detected` error: <https://github.com/sebastienros/jint/blob/d098d6e0242acaa89cfac7bde1e8fe62bdb51593/Jint/Native/Json/JsonSerializer.cs#L306>

However, I would like to ignore the cyclic reference; is there a built-in way to do that? looking at the code, it doesn't look like it though

Thanks!

**Comment by sebastienros** [comment]
What's the behavior in chrome?

**Comment by 0xFireball** [comment]
It would be difficult to test in chrome because I'm emulating some special APIs. It should, however, work in Node. If that's all right, I'll let you know soon.



On Tue, Nov 15, 2016 at 2:36 PM -0800, "Sébastien Ros" <notifications@github.com<mailto:notifications@github.com>> wrote:


What's the behavior in chrome?

-

**Comment by superyyrrzz** [comment]
Here's the repro code:
``` cs
            engine.Execute(@"
    model = {a : []};
    model.b = model.a;
    JSON.stringify(model);
    ");
```
The error message:
```
Unhandled Exception: Jint.Runtime.JavaScriptException: Cyclic reference detected.
   at Jint.Engine.Execute(Program program)
   at Jint.Engine.Execute(String source)
   at TestJint.Program.Main(String[] args) in d:\project\TestJint\TestJint\Program.cs:line 32
```
Behavior in Chrome:

* input: `model = {a: []}; model.b = model.a; JSON.stringify(model);`
* output: `"{"a":[],"b":[]}"`

**Comment by sebastienros** [comment]
With respect to the standards which can be found here: https://www.ecma-international.org/ecma-262/5.1/#sec-15.12.3
It states that a `TypeError` should be thrown: 

> If stack contains value then throw a TypeError exception because the structure is cyclical.

Now I need to understand at what point your code is actually not a circular reference (because otherwise it would fail in Chrome). And find out why Jint doesn't work.
To be clear, even crhome doesn't support them, and your example is not showing a cyclic reference, but Jint thinks there is one.
Try this code to see:
```
obj = {};
obj.a = "foo";
obj.b = obj;
JSON.stringify(obj);
```
You'll get `Uncaught TypeError: Converting circular structure to JSON`

You can in the meantime override what is serialized by providing a second argument like this: http://stackoverflow.com/questions/10392293/stringify-convert-to-json-a-javascript-object-with-circular-reference

**Comment by superyyrrzz** [comment]
In my understanding, circular reference occurs when an child points to its parent, then the object will be infinite loop when stringify. Your sample is definite circular reference. In my sample above, I think it should be ok as two children points to the same object. Chrome also think so. Jint seems wrongly take it as circular reference.

**Comment by sebastienros** [comment]
I see the difference now. I will see how to fix it.
