### ISSUE TITLE
DateTime tests are failing when current culture is not in English

### ISSUE THREAD

**Issue by SammyROCK** [sebastienros/jint#392]
On DatePrototype.cs public JsValue ToString(JsValue thisObj, JsValue[] arg2) the method ToString uses CultureInfo.InvariantCulture for the conversion, which results in "Mon Jan 01 1900 00:00:00 GMT+13:00".

In EngineTests.cs public void TestDateToStringFormat(DateTime testDate) the DateTimeOffset's ToString does not specify a Culture, which according to Microsoft's reference source results in using the CurrentCulture, but my current culture is in Portuguese, therefore the resulting string in this test is "seg jan 01 1900 00:00:00 GMT+13:00", which makes the test fail.

Which behavior is the correct one, invariant or current culture?
I don't mind doing this quick fix and pull requesting, but I can't decide which one is the correct one by myself.

References:
https://github.com/sebastienros/jint/blob/master/Jint/Native/Date/DatePrototype.cs#L100
https://github.com/sebastienros/jint/blob/master/Jint.Tests/Runtime/EngineTests.cs#L1199
http://referencesource.microsoft.com/#mscorlib/system/datetimeoffset.cs,85b407cde54cb34e
http://referencesource.microsoft.com/#mscorlib/system/globalization/datetimeformatinfo.cs,d8a79667802e6102

**Comment by f-camera** [comment]
Hi @SammyROCK ,
I stumbled on the same test failure. As far as I can tell the test is verifying Date.prototype.toString() implementation which is described (see link below) as requested to return always a string formatted in American English.
In this case, I think it is the very test line 1199 that needs to be fixed since DateTimeOffset.ToString() uses current culture, which depends on each machine setup.
Plus, maybe, reviewing the DatePrototype class (Invariant vs. en-us?).

My 2 cents. ;-)

Links:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toString

**Comment by lahma** [comment]
The functionality is correct, just the test was problematic as it relied on user's culture. It has been fixed a while ago.
