### ISSUE TITLE
Truthy result support

### ISSUE THREAD

**Issue by engenb** [sebastienros/jint#424]
Is there an expected behavior for expressions that evaluate to truthy?

example:
```
var result = new Engine()
    .Execute("1")
    .GetCompletionValue()
    .IsBoolean();
```
result here is false

```
var result = new Engine()
    .Execute("1 == true")
    .GetCompletionValue()
    .IsBoolean();
```
result here is true

Is there a significant challenge to allow evaluation of truthy result values?  My workaround is to wrap all expressions I'm evaluating in `$"!!( {expression} )"` which I think will get the job done, but this is not ideal IMO.  Thoughts?

**Comment by Ghostbird** [comment]
Isn't your problem that IsBoolean() is a typechecking thing?
A truthy value may evaluate as true, without being a boolean. I think you're looking for an IsTrue() function.

`1` evaluates to true (is "truthy"), but is not a boolean, it is a string.
`1 == true` IS a boolean, since the result of the `==` operator is of the type boolean.

The double exclamation mark works, because the result of the `!` operator is boolean, but you are right. It is not the correct way to do things.

**Comment by engenb** [comment]
I agree. An IsTrue or even IsTruthy would be more clear in intent.

**Comment by sebastienros** [comment]
There is a ToBoolean in another class that does what you need.

**Comment by sebastienros** [comment]
I just checked, the solution is to do 

```
var jsValue = new Engine()
    .Execute("1")
    .GetCompletionValue();
var result = TypeConvert.ToBoolean(jsValue);
```
