### ISSUE TITLE
Is an object pool suggested for speed performance?

### ISSUE THREAD

**Issue by rushfrisby** [sebastienros/jint#695]
With some other javascript engines I found that instantiating the engine was very expensive and to combat this I created an object pool of engines. Would you suggest this approach for Jint as well or is creating an engine lightweight enough that it isn't needed?

**Comment by lahma** [comment]
There was some work done earlier to make engine instantiation faster,  https://github.com/sebastienros/jint/pull/625 . Engine will of course load features on demand so if you urilize all JS constructs the engine needs to initialize them lazily. Caching the parsed program helps too. 

Sharing engine has the problem of old global state. 
 Probably depends on your use case and scripts.

**Comment by sebastienros** [comment]
@lahma what is your opinion about being able to mark an ObjectInstance immutable, such that we would not be able to change the builtin constructors, or mark pre-defined properties as not configurable. This way we could just re-initalize the lexical environments and reuse the engines. The main benefit would be that these built-in elements wouldn't have to be re-created.

It doesn't seem very hard to do, at least for the most obvious properties and constructor objects. Also it should be easy to cover everything as it would mean anything that has a property name currently in the engine code.

Forgive me if that's something I have already asked somewhere else ;)

**Comment by sebastienros** [comment]
I can see these two levels of reusability:
- The first one being about what I suggested so that we can reuse the engine instances and more importantly the existing constructor instances. 
- The second one would be being able to take a snapshot of a state and restore it. This would prevent the execution of a script to reach a specific state, and internally we would clone this state of the engine. 

Maybe the second option is also the way to implement option 1. Though freezing a state (default engine state) is even faster for perf than having to clone a snapshot (allocations).

**Comment by sebastienros** [comment]
But yeah, option 1 means we would disallow things like `Math.max = null`

**Comment by lahma** [comment]
@rushfrisby I'm working on PR https://github.com/sebastienros/jint/pull/789 , you might want to follow that development and please chime in if it's missing something.

**Comment by ChrML** [comment]
Immutables is a nice solution to this. Keep a shared Math instance until you change it, then it becomes a new instance dedicated for that engine.
