### ISSUE TITLE
Iterating over C# LinkedList

### ISSUE THREAD

**Issue by biwa** [sebastienros/jint#785]
Apparently it's not possible to use JS array methods on LinkedList like it is on (for example) List. For example there's no forEach method. That makes using them a bit cumbersome. Is that intentional?

Here's an example demonstrating the behavior:

```cs
using System;
using System.Collections.Generic;
using Jint;

namespace JintTest
{
	class Test
	{
		private List<int> sl;
		private LinkedList<int> ll;

		public List<int> SL { get { return sl; } }
		public LinkedList<int> LL { get { return ll; } }

		public Test()
		{
			sl = new List<int>();
			sl.Add(321);
			sl.Add(654);
			sl.Add(987);

			ll = new LinkedList<int>();
			ll.AddLast(123);
			ll.AddLast(456);
			ll.AddLast(789);
		}
	}

	class Program
	{
		static void Main(string[] args)
		{
			Engine engine = new Engine(cfg => cfg.AllowClr(typeof(Program).Assembly));
			engine.SetValue("log", new Action<object>(Console.WriteLine));

			engine.Execute(@"

var JintTestNamespace = importNamespace('JintTest');

var test = new JintTestNamespace.Test();

// Works as expected
test.SL.forEach(function(item) { log(item); });

// Works
for(var it=test.LL.First; it != null; it = it.Next)
	log(it.Value);

// Object has no method 'forEach'
test.LL.forEach(function(item) { log(item); });


			");

			Console.Read();
		}
	}
}
```

**Comment by lahma** [comment]
The problem here is that JavaScript does indexing when performing such operations. Currently Jint only wraps the `LinkedList` and as it has no indexer it cannot be used efficiently like array or `List` when performing such array-like operations. If you aren't going to mutate the value there's the options to create a custom type mapper that builds `ArrayInstance` from the list and effectively disconnects it from original source, type mappers can be registered to engine.

Here's an example what happens to regular array currently (which might change as here we can do mutation, and [copying has been a problem](https://github.com/sebastienros/jint/issues/776)):

https://github.com/sebastienros/jint/blob/24cda031a81033f49fa70ad0d3c66cc083e4066e/Jint/Native/JsValue.cs#L355-L372

**Comment by sebastienros** [comment]
Got an exception when trying to access `forEach` on a variable that is `MyClass[]`.

**Comment by lahma** [comment]
I'm closing this as there's no real alternative in JS world to model a linked list. CLR interop should allow access to methods, otherwise should just convert to array instance when entering the engine.
